# .github/workflows/main.yml
name: Pipeline CI (Pruebas y Build Docker)

# Define cu치ndo se ejecutar치 este workflow: en cada push a la rama principal
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ----------------------------------------
      # PASO A: INSTALAR Y EJECUTAR PRUEBAS UNITARIAS
      # ----------------------------------------
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Instalar dependencias de la App
        run: npm install 

      - name: Ejecutar Pruebas Unitarias
        run: npm test

      # ----------------------------------------
      # PASO B: CONSTRUIR IMAGEN DOCKER (CI)
      # ----------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Construir la imagen Docker (Verificaci칩n de Build)
        uses: docker/build-push-action@v5
        with:
          context: .
          
          tags: elibarraza/gastos-app:ci-build
          load: true

      - name: Resultados de CI
        run: echo "Pruebas y Construcci칩n de Imagen exitosas."